[package]
name = "wchl25_icp_hackathon"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
candid = "0.9.11"
ic-cdk = "0.10.2"
ic-cdk-macros = "0.7"
ic-stable-structures = "0.6"
